### PR TITLE
Add harvester for DataONE

### PR DESCRIPTION
**Pull request by michaeljb**
https://www.pivotaltracker.com/story/show/77763710
https://github.com/nsidc/search-interface/pull/3

@Jkovarik

### CODE REVIEW

**Comment by michaeljb** [comment]
TODO:

- [ ] update `CHANGELOG.md`
- [ ] fixture test

**Comment by Jkovarik** [comment]
Ran a test ingest into integration, it appears keywords and/or the dataset links are not bringing in the right thing.

**Comment by michaeljb** [comment]
@Jkovarik 

What did you see wrong with the dataset links? I just did a harvest on my dev solr VM (http://dev.search-solr.mbrandt.dev.int.nsidc.org:8983/solr/nsidc_oai/query), and the links look like what I reported on the Pivotal ticket; they are structured as `https://cn.dataone.org/cn/v1/resolve/SOME_DATASET_IDENTIFIER`, and some links go to a different XML result, while many give an error like this:

```xml
<error detailCode="1020" errorCode="404" name="NotFound">
  <description>The object specified by knb-lter-bnz.354.11 does not exist at this node.</description>
  <div/>
  <div/>
</error>
```
\- https://cn.dataone.org/cn/v1/object/knb-lter-bnz.354.11

That's as good as we'll get with the links.

**Comment by Jkovarik** [comment]
@michaeljb it looks like a lot of the links are bad, the work was mostly to verify it's bad metadata and/or make sure there wasn't another programmatic way of generating them.

**Comment by michaeljb** [comment]
rebased, ready to go @Jkovarik

**Pull request merged**
